using CSMS.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CSMS.Services
{
    public class InvoicePdfService
    {
        private readonly string _outputFolder;

        public InvoicePdfService(string outputFolder = "wwwroot/invoices")
        {
            _outputFolder = outputFolder;

            if (!Directory.Exists(_outputFolder))
                Directory.CreateDirectory(_outputFolder);
        }

        /// <summary>
        /// Generates a PDF invoice and returns the file path.
        /// </summary>
        public string GeneratePdf(Invoice invoice)
        {
            if (invoice == null) throw new ArgumentNullException(nameof(invoice));

            var fileName = $"Invoice_{invoice.InvoiceNumber}.pdf";
            var filePath = Path.Combine(_outputFolder, fileName);

            var items = invoice.Items ?? new List<InvoiceItem>();

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header()
                        .Text($"Invoice #{invoice.InvoiceNumber}")
                        .SemiBold().FontSize(20).FontColor(Colors.Blue.Medium);

                    page.Content()
                        .Column(col =>
                        {
                            col.Spacing(5);

                            // Customer info
                            col.Item().Text($"Customer ID: {invoice.CustomerId}");
                            col.Item().Text($"Issue Date: {invoice.IssueDate:yyyy-MM-dd}");
                            if (invoice.DueDate.HasValue)
                                col.Item().Text($"Due Date: {invoice.DueDate:yyyy-MM-dd}");

                            col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                            // Items table
                            col.Item().Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.ConstantColumn(40); // No.
                                    columns.RelativeColumn(4); // Description
                                    columns.RelativeColumn();  // Quantity
                                    columns.RelativeColumn();  // Unit Price
                                    columns.RelativeColumn();  // Total
                                });

                                table.Header(header =>
                                {
                                    header.Cell().Text("#").SemiBold();
                                    header.Cell().Text("Description").SemiBold();
                                    header.Cell().AlignRight().Text("Qty").SemiBold();
                                    header.Cell().AlignRight().Text("Unit Price").SemiBold();
                                    header.Cell().AlignRight().Text("Total").SemiBold();
                                });

                                int index = 1;
                                foreach (var item in items)
                                {
                                    table.Cell().Text(index++);
                                    table.Cell().Text(item.Description);
                                    table.Cell().AlignRight().Text(item.Quantity);
                                    table.Cell().AlignRight().Text(item.UnitPrice.ToString("C"));
                                    table.Cell().AlignRight().Text(item.TotalPrice.ToString("C"));
                                }
                            });

                            col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                            // Totals
                            col.Item().AlignRight().Column(c =>
                            {
                                c.Item().Text($"Subtotal: {invoice.Subtotal:C}");
                                c.Item().Text($"Tax: {invoice.Tax:C}");
                                c.Item().Text($"Total: {invoice.TotalAmount:C}").SemiBold();
                                c.Item().Text($"Status: {invoice.Status}");
                            });
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Generated by CSMS - ").FontSize(10);
                            x.Span(DateTime.Now.ToString("yyyy-MM-dd HH:mm")).FontSize(10);
                        });
                });
            }).GeneratePdf(filePath);

            return filePath;
        }
    }
}
